<?php

namespace Database\Seeders;

use App\Models\Testimonial;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TestimonialSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Testimonial::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $testimonials = [
            [
                'customer_name' => 'Nguyễn Văn An',
                'customer_title' => 'Giám đốc Công ty TNHH ABC',
                'title' => 'Dịch vụ thuê tài xế tuyệt vời!',
                'content' => 'Tôi đã sử dụng dịch vụ thuê tài xế được 6 tháng và thực sự rất hài lòng. Tài xế chuyên nghiệp, lái xe an toàn và luôn đúng giờ. Dịch vụ này giúp tôi tiết kiệm thời gian và đảm bảo an toàn cho gia đình. Đặc biệt là khi đi công tác xa, tôi hoàn toàn yên tâm. Cảm ơn đội ngũ nhân viên nhiệt tình và tận tâm!',
                'rating' => 5,
                'is_featured' => true,
                'status' => true,
                'sort_order' => 1,
                'customer_email' => 'nguyenvanan@abc.com.vn',
                'customer_phone' => '0901234567',
                'reviewed_at' => now()->subDays(15),
            ],
            [
                'customer_name' => 'Lê Thị Mai',
                'customer_title' => 'Nhân viên ngân hàng',
                'title' => 'Dịch vụ xuất sắc, rất hài lòng!',
                'content' => 'Làm việc trong ngành ngân hàng, tôi cần một dịch vụ vận chuyển đáng tin cậy và chuyên nghiệp. Dịch vụ thuê tài xế này đã vượt quá mong đợi của tôi. Tài xế rất chu đáo, xe luôn sạch sẽ và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Tôi đã sử dụng được 8 tháng và rất hài lòng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 16,
                'customer_email' => 'lethimai@bank.vn',
                'customer_phone' => '0901678901',
                'reviewed_at' => now()->subDays(5),
            ],
            [
                'customer_name' => 'Trần Thị Bình',
                'customer_title' => 'Chủ doanh nghiệp',
                'title' => 'Chất lượng dịch vụ vượt trội',
                'content' => 'Là một doanh nhân bận rộn, tôi cần một dịch vụ thuê tài xế đáng tin cậy. Dịch vụ này đã đáp ứng mọi yêu cầu của tôi. Tài xế có kinh nghiệm, am hiểu đường xá và luôn cập nhật thông tin giao thông. Xe sạch sẽ, dịch vụ chu đáo. Tôi đã giới thiệu cho nhiều bạn bè và đối tác sử dụng. Rất hài lòng với sự lựa chọn này!',
                'rating' => 5,
                'is_featured' => true,
                'status' => true,
                'sort_order' => 2,
                'customer_email' => 'tranthibinh@gmail.com',
                'customer_phone' => '0912345678',
                'reviewed_at' => now()->subDays(23),
            ],
            [
                'customer_name' => 'Lê Văn Cường',
                'customer_title' => 'Kỹ sư xây dựng',
                'title' => 'An toàn và tiện lợi',
                'content' => 'Công việc của tôi thường xuyên phải di chuyển giữa các công trình. Dịch vụ thuê tài xế này giúp tôi có thể nghỉ ngơi trên đường đi và chuẩn bị tốt cho công việc. Tài xế rất chuyên nghiệp, lái xe an toàn và có kiến thức tốt về giao thông. Dịch vụ đặt xe dễ dàng, giá cả hợp lý. Tôi sẽ tiếp tục sử dụng lâu dài.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 3,
                'customer_email' => 'levancuong@construction.vn',
                'customer_phone' => '0923456789',
                'reviewed_at' => now()->subDays(8),
            ],
            [
                'customer_name' => 'Phạm Thị Dung',
                'customer_title' => 'Bác sĩ',
                'title' => 'Dịch vụ 5 sao thực sự!',
                'content' => 'Làm bác sĩ, tôi cần một dịch vụ vận chuyển đáng tin cậy và an toàn. Dịch vụ thuê tài xế này đã vượt quá mong đợi của tôi. Tài xế rất chu đáo, xe luôn sạch sẽ và có mùi hương dễ chịu. Họ còn chuẩn bị nước uống và khăn ướt. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ 24/7. Tôi rất hài lòng và sẽ giới thiệu cho đồng nghiệp.',
                'rating' => 5,
                'is_featured' => true,
                'status' => true,
                'sort_order' => 4,
                'customer_email' => 'phamthidung@hospital.vn',
                'customer_phone' => '0934567890',
                'reviewed_at' => now()->subDays(12),
            ],
            [
                'customer_name' => 'Hoàng Văn Em',
                'customer_title' => 'Giáo viên',
                'title' => 'Dịch vụ hoàn hảo cho gia đình',
                'content' => 'Gia đình tôi thường xuyên đi du lịch cuối tuần. Dịch vụ thuê tài xế này giúp chúng tôi có những chuyến đi an toàn và thoải mái. Tài xế rất thân thiện với trẻ em, lái xe cẩn thận và am hiểu các địa điểm du lịch. Xe rộng rãi, có đầy đủ tiện nghi. Dịch vụ đặt xe linh hoạt, có thể thay đổi lịch trình dễ dàng. Rất hài lòng!',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 5,
                'customer_email' => 'hoangvanem@school.edu.vn',
                'customer_phone' => '0945678901',
                'reviewed_at' => now()->subDays(19),
            ],
            [
                'customer_name' => 'Vũ Thị Phương',
                'customer_title' => 'Nhân viên văn phòng',
                'title' => 'Tiết kiệm thời gian và chi phí',
                'content' => 'Trước đây tôi thường xuyên gặp khó khăn khi đi làm vào giờ cao điểm. Từ khi sử dụng dịch vụ thuê tài xế, tôi có thể làm việc trên xe và đến văn phòng đúng giờ. Tài xế rất chuyên nghiệp, xe sạch sẽ và có wifi. Dịch vụ đặt xe qua app rất tiện lợi, giá cả minh bạch. Tôi đã tiết kiệm được nhiều thời gian và chi phí.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 6,
                'customer_email' => 'vuthiphuong@office.com',
                'customer_phone' => '0956789012',
                'reviewed_at' => now()->subDays(6),
            ],
            [
                'customer_name' => 'Đặng Văn Giang',
                'customer_title' => 'Chủ nhà hàng',
                'title' => 'Dịch vụ đáng tin cậy cho khách VIP',
                'content' => 'Nhà hàng của tôi thường xuyên phục vụ khách VIP và cần dịch vụ vận chuyển chất lượng cao. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu. Tài xế có ngoại hình đẹp, ăn mặc lịch sự và có kỹ năng giao tiếp tốt. Xe cao cấp, sạch sẽ và có đầy đủ tiện nghi. Khách hàng rất hài lòng với dịch vụ này.',
                'rating' => 5,
                'is_featured' => true,
                'status' => true,
                'sort_order' => 7,
                'customer_email' => 'dangvangiang@restaurant.vn',
                'customer_phone' => '0967890123',
                'reviewed_at' => now()->subDays(14),
            ],
            [
                'customer_name' => 'Ngô Thị Hoa',
                'customer_title' => 'Nhân viên bán hàng',
                'title' => 'Dịch vụ tuyệt vời cho công việc',
                'content' => 'Công việc bán hàng của tôi đòi hỏi phải di chuyển nhiều giữa các cửa hàng. Dịch vụ thuê tài xế này giúp tôi tiết kiệm thời gian và có thể chuẩn bị tốt cho các cuộc hẹn. Tài xế rất thân thiện, lái xe an toàn và am hiểu đường xá. Dịch vụ đặt xe nhanh chóng, giá cả hợp lý. Tôi rất hài lòng với chất lượng dịch vụ.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 8,
                'customer_email' => 'ngothihoa@sales.com',
                'customer_phone' => '0978901234',
                'reviewed_at' => now()->subDays(11),
            ],
            [
                'customer_name' => 'Lý Văn Inh',
                'customer_title' => 'Kế toán trưởng',
                'title' => 'Dịch vụ chuyên nghiệp và đáng tin cậy',
                'content' => 'Làm kế toán, tôi cần một dịch vụ vận chuyển đáng tin cậy và chuyên nghiệp. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chu đáo, xe luôn sạch sẽ và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Tôi đã sử dụng được 1 năm và rất hài lòng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 9,
                'customer_email' => 'lyvaninh@accounting.vn',
                'customer_phone' => '0989012345',
                'reviewed_at' => now()->subDays(17),
            ],
            [
                'customer_name' => 'Trịnh Văn Khoa',
                'customer_title' => 'Kỹ sư IT',
                'title' => 'Dịch vụ hiện đại và tiện lợi',
                'content' => 'Làm IT, tôi đánh giá cao những dịch vụ có công nghệ hiện đại. Dịch vụ thuê tài xế này có app đặt xe rất thân thiện, giao diện đẹp và dễ sử dụng. Tài xế rất chuyên nghiệp, xe có wifi và sạc điện thoại. Dịch vụ đặt xe nhanh chóng, theo dõi hành trình real-time. Tôi rất hài lòng với trải nghiệm sử dụng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 10,
                'customer_email' => 'trinhvankhoa@tech.vn',
                'customer_phone' => '0990123456',
                'reviewed_at' => now()->subDays(9),
            ],
            [
                'customer_name' => 'Bùi Thị Lan',
                'customer_title' => 'Nhân viên marketing',
                'title' => 'Dịch vụ chất lượng cao',
                'content' => 'Công việc marketing đòi hỏi tôi phải tham dự nhiều sự kiện và hội thảo. Dịch vụ thuê tài xế này giúp tôi luôn đến đúng giờ và có vẻ ngoài chỉn chu. Tài xế rất thân thiện, xe sạch sẽ và có đầy đủ tiện nghi. Dịch vụ đặt xe linh hoạt, có thể thay đổi lịch trình dễ dàng. Tôi rất hài lòng và sẽ tiếp tục sử dụng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 11,
                'customer_email' => 'buithilan@marketing.com',
                'customer_phone' => '0901123456',
                'reviewed_at' => now()->subDays(13),
            ],
            [
                'customer_name' => 'Hồ Văn Minh',
                'customer_title' => 'Chủ xưởng sản xuất',
                'title' => 'Dịch vụ đáng tin cậy cho doanh nghiệp',
                'content' => 'Xưởng sản xuất của tôi thường xuyên cần vận chuyển khách hàng và đối tác. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của chúng tôi. Tài xế rất chuyên nghiệp, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ doanh nghiệp 24/7. Khách hàng rất hài lòng với dịch vụ này.',
                'rating' => 5,
                'is_featured' => true,
                'status' => true,
                'sort_order' => 12,
                'customer_email' => 'hovanminh@factory.vn',
                'customer_phone' => '0901234567',
                'reviewed_at' => now()->subDays(20),
            ],
            [
                'customer_name' => 'Đinh Thị Nga',
                'customer_title' => 'Nhân viên tư vấn',
                'title' => 'Dịch vụ hoàn hảo cho công việc',
                'content' => 'Công việc tư vấn đòi hỏi tôi phải di chuyển nhiều giữa các văn phòng. Dịch vụ thuê tài xế này giúp tôi tiết kiệm thời gian và có thể chuẩn bị tốt cho các cuộc hẹn. Tài xế rất thân thiện, lái xe an toàn và am hiểu đường xá. Dịch vụ đặt xe nhanh chóng, giá cả hợp lý. Tôi rất hài lòng với chất lượng dịch vụ.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 13,
                'customer_email' => 'dinhthinga@consulting.vn',
                'customer_phone' => '0901345678',
                'reviewed_at' => now()->subDays(7),
            ],
            [
                'customer_name' => 'Võ Văn Oanh',
                'customer_title' => 'Nhân viên kinh doanh',
                'title' => 'Dịch vụ tuyệt vời cho khách hàng',
                'content' => 'Làm kinh doanh, tôi cần một dịch vụ vận chuyển chất lượng cao để phục vụ khách hàng. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chuyên nghiệp, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Khách hàng rất hài lòng với dịch vụ này.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 14,
                'customer_email' => 'vovanoanh@business.vn',
                'customer_phone' => '0901456789',
                'reviewed_at' => now()->subDays(16),
            ],
            [
                'customer_name' => 'Lâm Thị Phương',
                'customer_title' => 'Nhân viên hành chính',
                'title' => 'Dịch vụ đáng tin cậy và tiện lợi',
                'content' => 'Công việc hành chính đòi hỏi tôi phải di chuyển nhiều giữa các phòng ban. Dịch vụ thuê tài xế này giúp tôi tiết kiệm thời gian và có thể chuẩn bị tốt cho công việc. Tài xế rất thân thiện, lái xe an toàn và am hiểu đường xá. Dịch vụ đặt xe nhanh chóng, giá cả hợp lý. Tôi rất hài lòng với chất lượng dịch vụ.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 15,
                'customer_email' => 'lamthiphuong@admin.com',
                'customer_phone' => '0901567890',
                'reviewed_at' => now()->subDays(10),
            ],
            [
                'customer_name' => 'Trần Văn Quý',
                'customer_title' => 'Luật sư',
                'title' => 'Dịch vụ chuyên nghiệp cho ngành luật',
                'content' => 'Làm luật sư, tôi cần một dịch vụ vận chuyển đáng tin cậy và chuyên nghiệp để đảm bảo đến tòa án đúng giờ. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chu đáo, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Tôi rất hài lòng và sẽ tiếp tục sử dụng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 17,
                'customer_email' => 'tranvanquy@law.vn',
                'customer_phone' => '0901789012',
                'reviewed_at' => now()->subDays(3),
            ],
            [
                'customer_name' => 'Nguyễn Thị Sinh',
                'customer_title' => 'Nhân viên bảo hiểm',
                'title' => 'Dịch vụ hoàn hảo cho công việc',
                'content' => 'Công việc bảo hiểm đòi hỏi tôi phải di chuyển nhiều giữa các văn phòng và nhà khách hàng. Dịch vụ thuê tài xế này giúp tôi tiết kiệm thời gian và có thể chuẩn bị tốt cho các cuộc hẹn. Tài xế rất thân thiện, lái xe an toàn và am hiểu đường xá. Dịch vụ đặt xe nhanh chóng, giá cả hợp lý. Tôi rất hài lòng với chất lượng dịch vụ.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 18,
                'customer_email' => 'nguyenthisinh@insurance.vn',
                'customer_phone' => '0901890123',
                'reviewed_at' => now()->subDays(1),
            ],
            [
                'customer_name' => 'Phạm Văn Tài',
                'customer_title' => 'Nhân viên bất động sản',
                'title' => 'Dịch vụ tuyệt vời cho khách hàng',
                'content' => 'Làm bất động sản, tôi cần một dịch vụ vận chuyển chất lượng cao để phục vụ khách hàng. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chuyên nghiệp, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Khách hàng rất hài lòng với dịch vụ này.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 19,
                'customer_email' => 'phamvantai@realestate.vn',
                'customer_phone' => '0901901234',
                'reviewed_at' => now()->subDays(2),
            ],
            [
                'customer_name' => 'Lê Văn Uy',
                'customer_title' => 'Nhân viên du lịch',
                'title' => 'Dịch vụ đáng tin cậy cho ngành du lịch',
                'content' => 'Làm du lịch, tôi cần một dịch vụ vận chuyển đáng tin cậy và chuyên nghiệp để phục vụ khách hàng. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chu đáo, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Khách hàng rất hài lòng với dịch vụ này.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 20,
                'customer_email' => 'levanuy@tourism.vn',
                'customer_phone' => '0901012345',
                'reviewed_at' => now()->subDays(4),
            ],
            [
                'customer_name' => 'Võ Thị Xuân',
                'customer_title' => 'Nhân viên y tế',
                'title' => 'Dịch vụ an toàn cho ngành y tế',
                'content' => 'Làm việc trong ngành y tế, tôi cần một dịch vụ vận chuyển đáng tin cậy và an toàn. Dịch vụ thuê tài xế này đã vượt quá mong đợi của tôi. Tài xế rất chu đáo, xe luôn sạch sẽ và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Tôi rất hài lòng và sẽ giới thiệu cho đồng nghiệp.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 21,
                'customer_email' => 'vothixuan@healthcare.vn',
                'customer_phone' => '0901123456',
                'reviewed_at' => now()->subDays(6),
            ],
            [
                'customer_name' => 'Đỗ Văn Yên',
                'customer_title' => 'Nhân viên giáo dục',
                'title' => 'Dịch vụ hoàn hảo cho ngành giáo dục',
                'content' => 'Làm việc trong ngành giáo dục, tôi cần một dịch vụ vận chuyển đáng tin cậy và chuyên nghiệp. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chu đáo, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Tôi đã sử dụng được 6 tháng và rất hài lòng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 22,
                'customer_email' => 'dovanyen@education.vn',
                'customer_phone' => '0901234567',
                'reviewed_at' => now()->subDays(8),
            ],
            [
                'customer_name' => 'Lý Thị Zương',
                'customer_title' => 'Nhân viên tài chính',
                'title' => 'Dịch vụ chuyên nghiệp cho ngành tài chính',
                'content' => 'Làm việc trong ngành tài chính, tôi cần một dịch vụ vận chuyển đáng tin cậy và chuyên nghiệp. Dịch vụ thuê tài xế này đã đáp ứng mọi yêu cầu của tôi. Tài xế rất chu đáo, xe cao cấp và có đầy đủ tiện nghi. Dịch vụ đặt xe qua app rất tiện lợi, hỗ trợ khách hàng 24/7. Tôi rất hài lòng và sẽ tiếp tục sử dụng.',
                'rating' => 5,
                'is_featured' => false,
                'status' => true,
                'sort_order' => 23,
                'customer_email' => 'lythizuong@finance.vn',
                'customer_phone' => '0901345678',
                'reviewed_at' => now()->subDays(5),
            ],
        ];

        foreach ($testimonials as $testimonialData) {
            Testimonial::create($testimonialData);
        }

        $this->command->info('Đã tạo ' . count($testimonials) . ' đánh giá 5 sao mẫu từ khách hàng thật.');
    }
}
